// <auto-generated />
namespace SalonAndSpaReservation.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TwlelvethMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TwlelvethMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202205111534357_Twlelveth Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
